### ISSUE TITLE
Disable the writing of empty sw2 output files 

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/SOILWAT2#109]
Unnecessary empty sw2_ output files are being written if the user does not request output for those variable/time period combinations. Code should be modified so only the output files (variables/time periods) that the user requests are being created.

**Comment by BrendenBe1** [comment]
This issue should be resolved once we switch the final output to only be for day and year.

**Comment by kpalmqui** [comment]
Sounds good. I would also like to continue to retain the options that already exist to save monthly transpiration, AET, precipitation, and temperature (in addition to daily and yearly values).

**Comment by kpalmqui** [comment]
This issue has been resolved with the changes to the outsetup_v30.in.

**Comment by kpalmqui** [comment]
This is a problem again. I requested daily and yearly TEMP and PRECIP using -o -i and several empty, unncessary soil layer files were written for both daily and yearly output.

**Comment by kpalmqui** [comment]
This issue has been resolved on my end as well.
