### ISSUE TITLE
Check that functional composition is being grabbed correctly when using STEPWAT2

### ISSUE THREAD

**Issue by CaitlinA** [DrylandEcology/SOILWAT2#110]
Small code addition in get_dSWA. Use v->fractionShrub, v->fractionGrass, v->fractionForb, and v->fractionTree instead of useVegType. V->fraction shrub etc. are calculated based on this last year’s STEPPE biomass on lines 303-314 in update_productivity in sxw_soilwat.c. This function is called right before SOILWAT2 runs within STEPWAT2. These values are updated every year based on STEPPE biomass, rather than using the fixed inputs for vegetation composition within SOILWAT2.

**Comment by BrendenBe1** [comment]
Issue should be resolved in latest commit. Converted useVegType to 2D array that stores fixed input and updated fractions

**Comment by kpalmqui** [comment]
Our goal with this fix was to utilize the v->fraction variable that already exists within SOILWAT2 and remove the redundant new variable useVegType. V->fraction should pass the correct vegetation fraction, whether SOILWAT2 standalone or STEPWAT2 is running. @BrendenBe1 @dschlaep

**Comment by BrendenBe1** [comment]
I can change it back to use the v->fraction values. One thing I am wondering about is the original reason I created the useVegType variable was to store the fixed inputs to check if we were using them or not. In the sxw_soilwat.c file around line 300 where the new fraction calculations are occurring they are sometimes being set to zero which would mean not to use that veg type in the SW_Output.c calculations for that timeperiod. Is that what is supposed to happen?

**Comment by kpalmqui** [comment]
In sxw_soilwat.c, the veg fractions are being set to 0 when no vegetation is established in STEPPE (totbmass=0). They would also be set to 0 if a particular VegType was not established (0 biomass, even if totbmass>0).  So, yes, if the veg fraction is set to 0, that type is not established within STEPPE and should not receive any SWA.

**Comment by BrendenBe1** [comment]
Issue should be resolved with commit https://github.com/DrylandEcology/STEPWAT2/commit/0e5eafcc4fe5d5914232892ff5ff4657c08ad66d
