### ISSUE TITLE
Get additional SOILWAT2 variables outputted in STEPWAT2 (besides the ones that are already available).

### ISSUE THREAD

**Issue by CaitlinA** [DrylandEcology/SOILWAT2#112]
At annual and daily level

**Comment by CaitlinA** [comment]
@BrendenBe1

**Comment by CaitlinA** [comment]
This is across both SOILWAT2 and STEPPEWAT2

**Comment by BrendenBe1** [comment]
Issue should be resolved with latest commit

**Comment by CaitlinA** [comment]
Great! @kpalmqui Do you want to check this so we can officially close the issue?

**Comment by kpalmqui** [comment]
Currently the outsetup_v30.in only has a subset of the time periods for each variable, but those appear to be working. I will add the rest of the time periods and look more closely at the output over the next 24 hours.

**Comment by kpalmqui** [comment]
To explain my previous comment further: we discussed saving daily and yearly output for all SOILWAT2 variables. Yet the outsetup_30.in is not populated properly for this. This will need to be added.
