### ISSUE TITLE
Duplicate empty files that end with _1 generated when running with -o

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/SOILWAT2#119]
When running with just the -o option, I am getting duplicate empty files that end with _1. WIth the -o option, no iteration files should be generated, so something is going wrong here.

**Comment by BrendenBe1** [comment]
Did you check if the files with the _1 were created at the same time as the others? It may have been left over from a previous run. I am unable to duplicate this problem.

**Comment by kpalmqui** [comment]
I am not longer able to re-create this.
