### ISSUE TITLE
Missing STD column for Temp_avg when saving SOILWAT2 output with -o option

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/SOILWAT2#121]
All standard deviation (STD) columns are present for SOILWAT2 output variables when using the -o option, except Temp_avg. It would be great to add a STD column for this variables as well.

**Comment by BrendenBe1** [comment]
The reason I did not add the standard deviation for temp is that in my testing for temp the values never changed over iterations. The temperature was always the same for every day in every iteration. If this is not always the case I can add the standard deviation

**Comment by kpalmqui** [comment]
If the yearly temperature changes from iteration to iteration (which it will when the Markov weather generator is being used, after the first 30 years of historical weather data), then the daily temperatures should change as well.

**Comment by BrendenBe1** [comment]
I will add that column for temperature then.
