### ISSUE TITLE
Function `create_col_headers` uses `SW_OUT_set_colnames`

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/SOILWAT2#125]
The new function `SW_OUT_set_colnames` defines the column names for SOILWAT output. There should be a unified effort via SOILWAT2 to produce a coherent set of output column names all uses of SOILWAT2.

**Comment by BrendenBe1** [comment]
Adding these functions to the branch soilwat_save_output and altering them to work with new output format
