### ISSUE TITLE
New SWA values are still 0 in iteration files.

### ISSUE THREAD

**Issue by BrendenBe1** [DrylandEcology/SOILWAT2#127]

**Comment by BrendenBe1** [comment]
@kpalmqui Check that it is fixed

**Comment by kpalmqui** [comment]
When yearly output for SWA is requested, the values for each iteration are still 0. However, the file which contains averages values across all iterations (sw_yearly_slyrs.csv) is populated with non-zero values for SWA.

The iteration files for daily SWA look good.

I attach the outsetup_v30.in file (quite simplified) I used and an iteration file for your convenience. 

[outsetup_v30.txt](https://github.com/DrylandEcology/SOILWAT2/files/1616897/outsetup_v30.txt)
[sw2_yearly_slyrs_1.xlsx](https://github.com/DrylandEcology/SOILWAT2/files/1616898/sw2_yearly_slyrs_1.xlsx)

**Comment by kpalmqui** [comment]
daily and yearly SWA values in iteration files are now non-zero when run with options USE_TIMESTEP=1.

**Comment by BrendenBe1** [comment]
For SWA we do need to have SWCBULK or else all the SWA values will be 0.

**Comment by kpalmqui** [comment]
Yes I know. We should add that to the outsetup_v30.in file.

My comment above says the values are now non-zero (i.e. the issue is fixed).
