### ISSUE TITLE
Move new output file code to `SW_Output.c`

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/SOILWAT2#150]
Adding
```
#include "SW_Defines.h"
#include "SW_Files.h"
#include "SW_Output.h"
```
to `filefuncs.c` should make you think about adding `SW_` code to this module. All what is added seems to fit much better and with fewer includes and externed to `SW_Output.c` - no?

**Comment by BrendenBe1** [comment]
@dschlaep Can you elaborate on this issue? I am a little confused what you mean by this issue. Thanks.

**Comment by dschlaep** [comment]
I was trying to point out that so far `filefuncs.c` was written so that the code did not depend on any of the structures defined by SOILWAT2 code. This is also reflected by the scope of this module
```
/* filefuncs.h -- contains definitions related to */
/* some generic file management functions
```

I think there are benefits to keep it this way, to keep it simple.

Your new code requires three new `#include` statements and one new global variable in `filefuncs`. The new functions, however, are only used by the module `SW_Output`.

This is why I was trying to ask the question where the new functions would fit better.

**Comment by BrendenBe1** [comment]
I could move this to SW_Files.c. I would need to add 1 include statement for SW_Output.h and need to create the global variable. It would be 2 less #include statements though. if that is still to much we could move the file_status structure to the SW_Files.h and then only need to do the global variable and no more include statements.

**Comment by dschlaep** [comment]
Why not place them in `SW_Output.c`? That is the only module where these specific functions are and will be used.

**Comment by BrendenBe1** [comment]
I moved the functions to SW_Output.c.
