### ISSUE TITLE
New line `USE_TIMESTEP 1` in input file `outsetup.in`

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/SOILWAT2#151]
Sure this works, but why convert something simple that worked well into something more complicated and more difficult to maintain?

**Comment by BrendenBe1** [comment]
I removed the USE_TIMESTEP line from both SOILWAT and STEPWAT outsetup.in files. This functionality has been replaced in SW_Output.c with a check to see which timeperiods are defined and then creating the files for those timeperiods if not using TIMESTEP.
