### ISSUE TITLE
Why was the CO2 multiplier initialization removed?

### ISSUE THREAD

**Issue by Zachary-Kramer** [DrylandEcology/SOILWAT2#158]
In https://github.com/DrylandEcology/SOILWAT2/commit/2063e38643b7ad49ce0eade239e8093886c7c123 you refactored the vegetation aspect of CO2 effects, but in the process you removed the initialization of `co2_multipliers`. Previously, all of its values were set to `1.0`:

```
-  PFTs default_values;		
 -  default_values.grass = default_values.shrub = default_values.tree = default_values.forb = 1.0;		
 -		
 -  for (year = 0; year < MAX_CO2_YEAR; year++)		
 -  {		
 -    c->co2_multipliers[BIO_INDEX][year] = default_values;		
 -    c->co2_multipliers[WUE_INDEX][year] = default_values;		
 -  }
```

This is utilized later in the code (emphasis: 2nd comment)
```
  // For efficiency, don't read carbon.in if neither multiplier is being used
  // We can do this because SW_CBN_CONSTRUCT already populated the multipliers with default values
  if (!c->use_bio_mult && !c->use_wue_mult)
  {
    #ifdef SWDEBUG
    if (debug) {
      swprintf("'SW_CBN_read': CO2-effects are turned off; don't read CO2-concentration data from file.\n");
    }
    #endif
    return;
  }
```

So now, if CO2 effects are disabled in SOILWAT2, the biomass values will be ruined. Or am I missing something? We must either populate it with default values or check if CO2 effects are being used before applying them.

**Comment by dschlaep** [comment]
In my reading of the code: It wasn't removed; it was moved from function `SW_CBN_construct` to `SW_VPD_construct` with the commit that you reference: https://github.com/DrylandEcology/SOILWAT2/commit/2063e38643b7ad49ce0eade239e8093886c7c123.

@Zachary-Kramer Have you actually produced output and detected a problem when you  formulated this issue (if so would you please show the problematic values) -- or read only (part of) the code?

`testing` case output based on latest master branch commit 7f58d91f38ca39925327a886f18bb4ca11471844 looks as expected:
- with CO2-effects on:
```
1980 | 179.613726 | 278.612432 | 15000 | 179.613726 | 15637.8399 | 50.44482 | 91.162587 | 1219.06354 | 50.44482 | 1411.11577 | 0.979168 | 0.979168 | 0.979168 | 0.979168 | 1.034133 | 1.034133 | 1.034133 | 1.034133
1981 | 179.953076 | 279.172877 | 15000 | 179.953076 | 15639.079 | 50.633151 | 91.456603 | 1220.75714 | 50.633151 | 1413.48005 | 0.980528 | 0.980528 | 0.980528 | 0.980528 | 1.03185 | 1.03185 | 1.03185 | 1.03185
1982 | 180.14705 | 279.473801 | 15000 | 180.14705 | 15639.7679 | 50.687729 | 91.555185 | 1222.07301 | 50.687729 | 1415.00365 | 0.981585 | 0.981585 | 0.981585 | 0.981585 | 1.030082 | 1.030082 | 1.030082 | 1.030082
```
- without CO2-effects:
```
1980 | 183.435131 | 284.540102 | 15000 | 183.435131 | 15651.4104 | 51.518069 | 93.102134 | 1244.99995 | 51.518069 | 1441.13822 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1
1981 | 183.526734 | 284.716924 | 15000 | 183.526734 | 15651.7704 | 51.638666 | 93.272825 | 1244.99995 | 51.638666 | 1441.55011 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1
1982 | 183.526734 | 284.716924 | 15000 | 183.526734 | 15651.7704 | 51.638666 | 93.272825 | 1244.99995 | 51.638666 | 1441.55011 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1
```

**Comment by Zachary-Kramer** [comment]
You are right. The diff hides SW_VegProd.c; it appears I missed it when quickly skimming the changes. I will update the comment to reflect the new location. I tried testing before posting, but my SOILWAT2 clone was having issues compiling (fixed now).

Thanks
