### ISSUE TITLE
SWA output for individual iterations all 0 in sw2_yearly_slyrs_x.csv files

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/SOILWAT2#160]
SWA values are all 0 in the yearly individual iteration files.

**Comment by BrendenBe1** [comment]
It seems this only occurs when -o and -i are run together. Looking into why.

**Comment by BrendenBe1** [comment]
This should be resolved in latest commit. @kpalmqui could you test this and see if it works on mac?

**Comment by kpalmqui** [comment]
Yes, the issue is also resolved on my end.
