### ISSUE TITLE
SW_VWCBulkRes function invalid for some parameter values

### ISSUE THREAD

**Issue by nip5** [DrylandEcology/SOILWAT2#171]
SW_VWCBulkRes function in the SW_SoilWater.c file is invalid for some parameter values. The issue is addressed as a comment but never implemented in the code.

**Comment by CaitlinA** [comment]
@nip5  Are you referring to the comment from 2/03/2012?

Are you suggesting to fix it by enforcing that the equation only be used when when the input clay and sand are within limits in this comment?

**Comment by nip5** [comment]
Yes if it doesn't mess anything else up, I don't know the code good enough to say. I do know that changing it doesn't effect any of the current unit tests.

**Comment by CaitlinA** [comment]
@dschlaep might have better insight into this.

The function is only ever called when determining the swcBulk_min. Perhaps when input clay and sand values are out of bounds, the SW_VWCBulkRes should return NA or some high value so that for this line of code:
			"lyr->swcBulk_min = fmax(0., fmin(swcmin_help1, swcmin_help2));"
swcmin_help2 is returned.

**Comment by dschlaep** [comment]
@nip5 please assign issue to a milestone (see our guidelines)
