### ISSUE TITLE
Add debug as an argument to functions

### ISSUE THREAD

**Issue by CaitlinA** [DrylandEcology/SOILWAT2#188]
Could we add a debug flag to function (i.e. the functions in SW_Flow_Lib.c) arguments instead of having the debug hard-coded within the function?

I think this would be useful when debugging unit-tests. I want the debugger to print once for a specific test, instead of every time SOILWAT2 and the function is calling during the unit-testing process.

Does that make sense?

**Comment by dschlaep** [comment]
Please also avoid developing code that behaves differently in production and testing environments. See for instance the following discussions
- https://stackoverflow.com/questions/17904236/is-a-check-like-isinunittest-an-antipattern
- https://stackoverflow.com/questions/3167617/determine-if-code-is-running-as-part-of-a-unit-test

And remember for instance this case where code behaved differently between production and testing environments: "The agency [EPA] had found that Volkswagen had intentionally programmed ... diesel engines to activate their emissions controls only during laboratory emissions testing which caused the vehicles' NOx output to meet US standards during regulatory testing, but emit up to 40 times more NOx in real-world driving." (https://en.wikipedia.org/wiki/Volkswagen_emissions_scandal)

**Comment by dschlaep** [comment]
@CaitlinA Can we mark this `wontfix` and close it?
