### ISSUE TITLE
Memory allocation is not balanced with free

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/SOILWAT2#197]
For instance, the memory allocation for soil layers (function `_newlayer`) is balanced by freeing that memory (function `SW_SIT_clear_layers`).

Shoudn't we have a counterpart to `SW_CTL_init_model`, e.g., `SW_CTL_clear_model`, which calls functions, e.g., `SW_MKV_deconstruct();`, to free the allocated memory from their init-counterparts, eg., `SW_MKV_construct`: which allocates memory, e.g.,
```
	m->wetprob = (RealD *) Mem_Calloc(MAX_DAYS, s, "SW_MKV_construct");
```
that is currently never freed.

Note also discussion in https://stackoverflow.com/questions/654754/what-really-happens-when-you-dont-free-after-malloc#654766 where some argue that freeing memory just before exiting is useless on modern OSes, but what are the consequences for libSOILWAT2 when used with `rSOILWAT2`?

@nip5 Any thoughts?

**Comment by nip5** [comment]
Unless we run `SW_CTL_init_model` multiple times in one execution I don't think it would make much of difference and from the looks of it, it doesn't look like we do. As you said modern OSes would just free it for us on exit anyway but it does make me wonder why we call `SW_SIT_clear_layers` then since it is also directly before the exit?

**Comment by dschlaep** [comment]
Thanks for the input! Ok, so we should be good for `SOILWAT2-standalone` and `STEPWAT2`. 

However, `rSOILWAT2` compiles `SOILWAT2`-code as shared object (`.so`/`.dll`). It calls `SW_CTL_init_model` from the c function `initSOILWAT2` (file `SW_R_lib.c`) which in turn is called by the c functions `onGetInputDataFromFiles` and `start` which are called from R functions `sw_inputDataFromFiles` and `sw_exec` respectively -- the latter being the main function to run a simulation (e.g., used repeatedly by `rSFSW2`). Does this count as "multiple times in one execution" -- what do you think about this for `rSOILWAT2`?

The function `SW_SIT_clear_layers` was written mainly for use by `rSOILWAT2` where it is called at the end of the same functions as above, i.e., `onGetInputDataFromFiles` and `start` -- I guess we could remove it from `main` in `SOILWAT2-standalone`?

**Comment by nip5** [comment]
I don't think we need to free it, even for `rSOILWAT2` the `SW_CTL_init_model` function exists just to create the various structures or reset them and it does this by modifying the structure addresses using `memset()` (and it resets to the same size) rather than allocating new memory each time.
