### ISSUE TITLE
Soilwat weather being affected by stepwat functions

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/SOILWAT2#226]
Currently Stepwat is using random numbers to determine plant mortality and reproduction. The number of calls to rand() is variable depending on the input parameters of Stepwat. This means that random numbers that were being generated for Soilwat are instead being used by Stepwat. Therefore, for a given random seed the weather data from Soilwat will change depending on the input parameters to Stepwat. This is clearly not ideal behavior since weather cannot be kept constant for different grazing levels.

The problem comes from the fact that only one instance of the rand() function is created per program. Every call to rand by any function will affect every future call to rand. To solve the problem I would like to implement two new functions and add some functionality to rands.c and rands.h:
1: Declare the bucket array at the top of rands.c so that it can be filled with random numbers to be used by STEPWAT and any other coupled programs to avoid variable calls to rand().
2: Declare an array index field in rands.c. The index will be incremented every time STEPWAT requests a random number. This will cycle through the preselected numbers to give the impression that they are being created on the fly. 
3: Add function RandUni_deterministic(). This function will pick the next number from the bucket array and divide it by RAND_MAX to return a value between 0 and 1.
4: Add function RandUniRange_deterministic(int first, int last). This function will pick the next number from the bucket array and use it to generate a random number between first and last.
5: Add parameter to RandBeta(float aa, float bb, Bool deterministic). Rather than copy the RandBeta function and change two lines to create a deterministic version, I think it makes more sense to pass a Bool value that determines if RandBeta calls RandUni() or RandUni_deterministic().

The _deterministic versions of RandUni and RandUniRange should be used everywhere that a random number is requested outside of Soilwat. This will ensure that for a given seed Soilwat output will not be affected by anything outside of Soilwat.

I already have this code written and tested, and I plan on opening a new branch to submit it.

If anyone has any comments or questions about this issue please let me know. I am especially interested in getting feedback about adding a parameter to the RandBeta function.

**Comment by kpalmqui** [comment]
@dschlaep @CaitlinA 

The random seed is not always working as expected in STEPWAT2. See description of this issue in https://github.com/DrylandEcology/STEPWAT2/issues/33#issuecomment-419180773. @chaukap has identified the problem and proposed a solution here (and also documented here https://github.com/DrylandEcology/STEPWAT2/issues/33#issuecomment-419180773), which needs to be implemented primarily in SOILWAT2.

Do either of you see any problems with his proposed fixed? If not, he will create a new SOILWAT2 development branch off master to implement this relatively simple fix.

**Comment by kpalmqui** [comment]
@dschlaep Thank you Daniel for clarifying how the random seed works in SOILWAT2, this is very helpful!

**Comment by chaukap** [comment]
Thanks for the explanation @dschlaep. I agree that I would rather not touch the SOILWAT2 functions. 

When SOILWAT and STEPWAT are both running when should the random seed be reset? If the seed is reset every iteration then I don't believe that this is the problem.  Since the weather generator and STEPWAT2 are both using RandUni() they could change eachother's outputs by calling RandUni() a variable number of times. For production runs this should be fine since the output will still be random and the results will be reasonable. For comparing different grazing levels it would be ideal if weather output was not affected by grazing frequency.

I could fix the bug by adding a ST_rand.c file to STEPWAT2 so it is no longer coupled to rand.c in SOILWAT2. This would correct the bug and help decouple the two programs. ST_rand.c would use a random algorithm similar to a hashing algorithm to generate random numbers for STEPWAT2 only. Let me know what you think!

**Comment by chaukap** [comment]
I've been doing some testing of the code and hopefully I can explain where the bug is coming from a little better. The resource_partitioning_overhaul branch of STEPWAT2 is currently using the latest version of SOILWAT so the array out-of-bounds errors have been removed. 

Setting the seed to 0 also works. With seed=0 the results are always random and unique. However, setting the seed to 7 and changing the grazing levels is affecting weather, specifically ppt, values. I made some tables to show where the bug comes from and how we can fix it. For my test I used three grazing levels; No Grazing, Low Grazing, and High Grazing.

I added this print statement to ST_resgroups.c at line 482 and used it to count the number of calls to RandUniRange(). If the program were running as expected, the same number of calls would occur no matter what changes are made to grazing frequency. What I found is that depending on the grazing parameters the number of calls to RandUniRange() changes. 

`if (ndv->killed && RandUni() < ndv->prob_veggrow) {
printf("RandUniRange() Called\n");
growth1 = s->relseedlingsize * RandUniRange(1, s->max_vegunits);`

I used the seed (1 100 7) to run this code. Since there is only one iteration the seed should not need to be reset.

Calls to RandUni() by vegetative growth:
--
Grazing level | Calls
No | 4
Low | 21
High | 1
--

This suggests that changes in biomass caused by grazing are resulting in more or less rand() calls. 
The problem isn't random number generation, it's changes in the order of which programs call rand().
Using the data above, the following is a sample of how rand() numbers could be given to different programs depending on number of calls. This is not the actual sequence of numbers but it serves to demonstrate how variable calls to RandUniRange() can affect the program.

Who is calling rand() for the given value:
--
rand() | no Grazing | low Grazing | high Grazing
0.066 | W | W | W
0.344 | W | W | W
0.815 | W | W | W
0.124 | S  | S  | S
0.843 | S  | S  | W
0.511 | S  | S  | W
0.736 | S  | S  | W
0.404 | W | S  | W
0.025 | W | S  | W
0.711 | W | S  | W
0.474 | W | S  | W
0.208 | W | S  | W
0.353 | W | S  | W
0.308 | W | S  | W
* W = weather generator
* S = STEPWAT2 function.

In this example the fifth value, 0.843, is grabbed by STEPWAT under no grazing or light grazing, but is grabbed by the weather generator under high grazing. This will offset all future calls to rand(). The next table shows the average ppt values for each run.

average ppt:
--
No Grazing | 563.69
Low Grazing | 555.39
High Grazing | 560.74
--

The only way to make the two programs completely independent is to prevent one from ever calling rand(). 

1. The implementation I have in the branch corresponding to this issue generates a fixed number of random numbers which Stepwat then iterates through. This prevents Stepwat from every calling rand() itself. 

Advantages:
* Can still use the rand() function by calling it a fixed number of times at the beginning of the program.
* Keeps all code related to random numbers in one file.

Disadvantages:
* limits the number of random numbers we can work with. This could skew the results for larger production runs.
* Future programmers can very easily reintroduce the bug by calling the wrong random number function.


2. Implement a separate random number generator in STEPWAT that does not use rand() at all. This would be pretty simple and would look similar to RandUni_good().

Advantages:
* Constant stream of random numbers that could not affect the weather generator.
* Decouples the two programs.

Disadvantages:
* Could not use rand() and therefore more code must be written.
* separates random number generation for the two programs.


Hopefully this clears up where the bug comes from. If you have any other questions let me know and I'll do my best to address them.

**Comment by dschlaep** [comment]
SOILWAT2 is not a different program from STEPWAT2 -- the code is completely integrated and it becomes one program.

**Comment by kpalmqui** [comment]
Thank you Chandler for this very clear explanation. @dschlaep does this expanded explanation help to understand what is going on here?

I believe Chandler means "repository" when he uses the word "program". To clarify, utilizing different grazing intensities allowed us to identify this problem, and Chandler uses this as an example to demonstrate the issue.

It seems to me like option 2. might be the best bet, unless I am missing something.

**Comment by dschlaep** [comment]
`srand()` operates globally and the computer doesn't care whether the code is written across files in different repositories or not -- the only thing that matters is that `STEPWAT2` is one executable which contains the code in the `SOILWAT2` repository.

**Comment by chaukap** [comment]
I was hoping to write my own random number generator that doesn't use the STL functions at all and use it for random numbers in STEPWAT2 only.

**Comment by dschlaep** [comment]
Why re-invent the wheel, if there are good multi-stream random number generators out there? 

e.g., http://www.pcg-random.org/using-pcg-c.html can handle 2^63 different streams simultaneously.

Each of the different processes gets is own dedicated 'RNG-sequence constant' / stream.

**Comment by chaukap** [comment]
The pcg random number generator looks good I think I'll take it that direction. I will close the branch corresponding to this issue and implement the new RNG in STEPWAT2. Thanks for your help, @dschlaep.

**Comment by dschlaep** [comment]
The pcg RNG should replace both `RandUni_fast` and `RandUni_good`, i.e., be called by `RandUni`.

Then each process, e.g., weather generator, grazing, mortality etc., will be assigned a unique `RNG-sequence constant`, create its own rng variable of type `pcg32_random_t`, initialize that with a call to `pcg32_srandom_r` using `seed` and its unique `RNG-sequence constant`, and then will pass this rng variable via the random variate functions via `RandUni` to `pcg32_srandom_r`, respectively via `RandUniRange` to `pcg32_boundedrand_r`. All our random variate functions will need a new argument representing the rng variable. 

Thus, we have a unified random number generator system and separate streams for each process.

**Comment by dschlaep** [comment]
maybe we should check on the licensing/permissions of using pcg

**Comment by chaukap** [comment]
I read the Apache licensing agreement and it should be free to use as long as we leave in the link to the licensing agreement and the copyright information. We will also need to document all changes we make so they are not confused with the original code.

**Comment by dschlaep** [comment]
Sounds good, thanks.

I guess the easiest would be to add https://github.com/imneme/pcg-c-basic as a submodule to `SOILWAT2` and then compile `SOILWAT2` (and `STEPWAT2`) including `pcg_basic.c` and `pcg_basic.h` -- what do you think? This way we don't make any changes, include all the original information, and still only have the functionality that we need?

**Comment by chaukap** [comment]
pcg-c-basic should have everything we need and adding the submodule seems like the way to go. 

As far as implementation I think I should add a few more issues to SOILWAT2 and STEPWAT2 to better document the transition. In SOILWAT we should define a few goals in regards to how the new code should behave with what we already have. Let me know what you think of these:
* The weather generator and STEPWAT2 should not deal directly with the pcg rng. Instead they should still call RandUni(), except include the rng variable corresponding to their stream.
* Each process should have a well defined stream domain. For example the weather generator could have constants 1u through 20u so that if additional functions need a stream they know what they can choose from.

**Comment by chaukap** [comment]
I will make a branch off of master to incorporate the pcg random number generator. I will also move this issue into a milestone of the same name.

**Comment by dschlaep** [comment]
Great, thanks!

Do you think adding information about the "stream domain constants" to the documentation is sufficient? Or, should we rather think about some centralized way to keep track of the next available stream constant?

**Comment by chaukap** [comment]
We could use a static variable to keep track of what stream would be given next. Instead of having each process pick its steam we could use a static variable in random.c to give out streams sequentially. Since the stream only needs to be specified once when calling pcg32_srandom_r(), none of the individual processes need to know their stream.

**Comment by dschlaep** [comment]
I like this idea; I think it has benefits hiding such details from the individual processes. However, this implementation needs to guarantee that each process receives the same stream during each run -- independent of inputs such as grazing level...

**Comment by chaukap** [comment]
Once the pcg rng is up and running I'll make sure that each process instanciates their rng in the same order every time and it should guarantee the same streams go to the same processes every time.

I am having some trouble getting the makefile to create the pcg_basic.o file into the /pcg directory and link it could I get some help with this?

**Comment by dschlaep** [comment]
ok, I'll take a look at the makefile

**Comment by dschlaep** [comment]
I just pushed commit 00ab61da8bd4bea0628b0f4a9de913661d5beb3d with corrected `.gitmodules` and updated `makefile` -- this compiles with the pcg code (and runs the unit tests and integration `testing/` case -- of course without yet calling the integrated pcg functions).

Let me know if you have questions.

**Comment by chaukap** [comment]
Thank you, @dschlaep. I'll work on issue #229 so rand.c uses the pcg functions then implement it in the weather generator

**Comment by dschlaep** [comment]
closed with #233
