### ISSUE TITLE
Change RandUniRange to RandUniFloatRange and RandUniIntRange

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/SOILWAT2#234]
RandUniFloatRange(float min, float max, *pcg32_basic_t) will generate a random float between the given bounds min and max.

RandUniIntRange(int min, int max, *pcg32_basic_t) will generate a random integer between the given bounds max and min.

All current calls to RandUniRange() will become calls to RandUniIntRange().

The reason for this change is functionality necessary in STEPWAT2. RandUniFloatRange() is needed in STEPWAT2 but since random generation is handled in SOILWAT2 this change is necessary.

**Comment by chaukap** [comment]
This issue has been resolved and the corresponding branch has been merged back into incorporate_pcg_rng.

**Comment by kpalmqui** [comment]
See documentation in https://github.com/DrylandEcology/STEPWAT2/issues/174#issuecomment-425548571 for further detail.

**Comment by kpalmqui** [comment]
Looks like we need to update the Description of RandUniFloatRange to review reference to integer values: 

\fn int RandUniIntRange(const long first, const long last)
	\brief Generate a random integer between two numbers.

	Return a randomly selected integer between
	first and last, inclusive.
