### ISSUE TITLE
Update SOILWAT2 to be compatible with gridded_code branch of STEPWAT2

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/SOILWAT2#247]
While updating STEPWAT2's gridded code I changed the variable Globals to a pointer. There is one reference to Globals in setGlobalSTEPWAT2_OutputVariables() in SW_Output_outarray.c that needs to be updated.
```
Globals.runModelYears to Globals->runModelYears
```

**Comment by chaukap** [comment]
The first build of 28f5cfa failed, but the rebuild succeeded. Looks like #210 was the culprit.

**Comment by chaukap** [comment]
This is the only change I needed to make. Unfortunately merging this into master right now would break STEPWAT2's master branch. I will therefore leave this open until the gridded_code milestone in STEPWAT is complete.

@dschlaep if you would like me to close the milestone or issue let me know, I feel bad about cluttering the repo with such a minor change.

**Comment by dschlaep** [comment]
@chaukap Sounds good. Not much of a problem. Feel free to create a pull-request though (with above explanation) to mark that this is ready to go once the STEPWAT2-side is -- at least for me, PRs are more visible and I am l less likely to forget about them when they are becoming stale...

**Comment by chaukap** [comment]
I identified one more problem: we are changing SXW to a pointer and there are a few places in SOILWAT that reference SXW. I will change these to pointers as well. Everything is still inside an #ifdef STEPWAT so this should not change SOILWAT.
