### ISSUE TITLE
Some compiler/versions fail for some types of unit tests

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/SOILWAT2#305]
- see also #300 and commit https://github.com/DrylandEcology/SOILWAT2/commit/546a9e1aa11a7d41a25921483348f63921bf2e87

- tested with https://github.com/DrylandEcology/SOILWAT2/releases/tag/v6.3.0

- compiler tested
    * gcc versions 9, 10, 11
    * clang versions 9, 10, 11, 12, 13

- tests (where `compiler` is either `gcc` or `clang` and `compiler++` is `g++` or `clang++` respectively):
  ```
    [1] CC=compiler CXX=compiler++ make clean test test_run
    [2] CC=compiler CXX=compiler++ make clean test_severe test_run
    [3] CC=compiler CXX=compiler++ ASAN_OPTIONS=detect_leaks=1 LSAN_OPTIONS=suppressions=.LSAN_suppr.txt make clean test_severe test_run
  ```

- errors with all gcc and tests [2] or [3] (no errors with [1]), e.g.:
> ./sw_test
AddressSanitizer:DEADLYSIGNAL
=================================================================
==20142==ERROR: AddressSanitizer: stack-overflow on address 0x7ffee0041ff8 (pc 0x00010c5c9cd7 bp 0x7ffee0042850 sp 0x7ffee0042000 T0)
    #0 0x10c5c9cd7  (libasan.6.dylib:x86_64+0xfcd7)
    #1 0x10d2077c7  (libubsan.1.dylib:x86_64+0x117c7)
>
> SUMMARY: AddressSanitizer: stack-overflow (libasan.6.dylib:x86_64+0xfcd7) 
==20142==ABORTING

- no errors with any clang; however, previously (January 2022), error with clang-13 and any test:
> Undefined symbols for architecture x86_64:
    "std::runtime_error::what() const", referenced from:
        vtable for testing::internal::GoogleTestFailureException in libgtest.a(gtest-all.o)
    ...

**Comment by N1ckP3rsl3y** [comment]
* Tested April 2022, I was able to replicate the error in relation to clang-13 with all tested compilers:
   - gcc versions 5, 7, 9, 10, 11
   - Clang versions 5.0, 9.0, 10, 11, 12, 13

* I was not able to replicate the error when running ```./sw_test```

**Comment by dschlaep** [comment]
outdated but see #364
