### ISSUE TITLE
Consistent unit test suit naming

### ISSUE THREAD

**Issue by N1ckP3rsl3y** [DrylandEcology/SOILWAT2#313]
Having a consistent naming of SOILWAT2's unit test suits would make the tests more organized and easier to read when testing. My suggestion for this is:

* Naming the test suit depending on the test file name. E.g. if we are in the file `test_SW_Weather.cc` we would make the suit "WeatherTest" or "WeatherFunctionsTest"

**Comment by dschlaep** [comment]
closed by 19973e1121ea65f3068cad6e0817515abf533599
