### ISSUE TITLE
Update compilation of tests to C++14

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/SOILWAT2#339]
Upcoming versions of googletests will require C++14, e.g.,
- ["The 1.12.x branch will be the last to support C++11. Future releases will require at least C++14."](https://github.com/google/googletest/blob/main/README.md)
- commit on main branch ["Add an explicit #error that C++ versions less than C++14 are not supported"](https://github.com/google/googletest/commit/b5401fef68794d93b7fcd933bc3692211e8ebad1)

**Comment by N1ckP3rsl3y** [comment]
As of commit https://github.com/DrylandEcology/SOILWAT2/commit/a49020152638b61a6b7f64fa0a6aea9441d54625, googletests use C++14.
