### ISSUE TITLE
Convoluted #if !defined(STEPWAT) && !defined(RSOILWAT) logic?

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/SOILWAT2#84]
Several occurrences of this or similar code snippet in `SW_Output.c` functions `get_xxx`, e.g., `get_vwcBulk`:
```
#if !defined(STEPWAT) && !defined(RSOILWAT)
	char str[OUTSTRLEN];
#elif defined(STEPWAT)
	char str[OUTSTRLEN];
#endif
```

This seems to be rather convoluted. Wouldn't this be the equivalent of
```
#ifndef RSOILWAT
	char str[OUTSTRLEN];
#endif
```

@BrendenBe1 You are working on the ouput code. Can you please voice your thoughts on this?

**Comment by BrendenBe1** [comment]
yes, the `#ifndef RSOILWAT` is equivalent. I will go through and make this change as well as minimize the #ifdef calls as much as possible.

**Comment by dschlaep** [comment]
Great, thanks.
