### ISSUE TITLE
SW_Model.month does not hit last month

### ISSUE THREAD

**Issue by BrendenBe1** [DrylandEcology/SOILWAT2#93]
Month is not being calculated properly in SW_Model.c; the month is going from 0-10 not 0-11 like it should be. instead of going to 11 it just has two 10's.

**Comment by dschlaep** [comment]
Could you give more details? Some code that demonstrates the problem?

- Which variable `month` are you talking about, e.g., `SW_Model.month`, `_prevmonth`, `mon` local to function `SW_VPD_read`, `month` local to function `interpolate_monthlyValues`, ...?
- Are you talking about the function `doy2month` or `doy2mday`?
- The macro `ForEachMonth`?
- The defined months in `Times.h`?

**Comment by dschlaep** [comment]
Issues with general bug reports should be assigned to milestone `master` as per our [guidelines, see 'Bugfix branches'](https://github.com/Burke-Lauenroth-Lab/workflow_guidelines).

**Comment by BrendenBe1** [comment]
In SW_Output.c when using STEPWAT  there is a statement `switch(pd)` that gets the timeperiod
`switch (pd)`
`{`
 `case eSW_Month:`
	`p = t->month-1;`
	`val = v->moavg.swcBulk[i];`
	`break;`
`}`
(ex from get_swcbulk function in master branch)

The months go from 0 to 11 normally but this repeats the last month. It will output
 "0 1 2 3 4 5 6 7 8 9 10 10"

**Comment by dschlaep** [comment]
Thanks for the details.

**Comment by dschlaep** [comment]
I guess you are referring to the logic branch for the condition `isPartialSoilwatOutput == TRUE` under STEPWAT2 in the function `get_swcBulk`?

You forgot `tOffset`. Look at the code for `SOILWAT2` standalone or if `RSOILWAT2` is defined.

Below demonstration is based on SOILWAT2 standalone and current master (commit https://github.com/Burke-Lauenroth-Lab/SOILWAT2/commit/2a9f262cca4aecbd418b05300d73174cfa5bf282):

I inserted following print statements in the function `get_swcBulk` directly after the call to `get_outstrleader`:
```
static void get_swcBulk(void) {
...
#if !defined(STEPWAT) && !defined(RSOILWAT)
	char str[OUTSTRLEN];
	get_outstrleader(pd);

if (pd == 2) swprintf("get_swcBulk: outstr=%s, tOffset=%d, yr=%d, mon=%d, doy=%d\n",
  outstr, tOffset, SW_Model.year, SW_Model.month, SW_Model.doy);

...
}
```

Output from `make cleaner bin bint bint_run`:
```
get_swcBulk: outstr=1980	1, tOffset=1, yr=1980, mon=1, doy=32
get_swcBulk: outstr=1980	2, tOffset=1, yr=1980, mon=2, doy=61
get_swcBulk: outstr=1980	3, tOffset=1, yr=1980, mon=3, doy=92
get_swcBulk: outstr=1980	4, tOffset=1, yr=1980, mon=4, doy=122
get_swcBulk: outstr=1980	5, tOffset=1, yr=1980, mon=5, doy=153
get_swcBulk: outstr=1980	6, tOffset=1, yr=1980, mon=6, doy=183
get_swcBulk: outstr=1980	7, tOffset=1, yr=1980, mon=7, doy=214
get_swcBulk: outstr=1980	8, tOffset=1, yr=1980, mon=8, doy=245
get_swcBulk: outstr=1980	9, tOffset=1, yr=1980, mon=9, doy=275
get_swcBulk: outstr=1980	10, tOffset=1, yr=1980, mon=10, doy=306
get_swcBulk: outstr=1980	11, tOffset=1, yr=1980, mon=11, doy=336
get_swcBulk: outstr=1980	12, tOffset=0, yr=1980, mon=11, doy=367
get_swcBulk: outstr=1981	1, tOffset=1, yr=1981, mon=1, doy=32
```

**Comment by dschlaep** [comment]
I believe this is a direct consequence of having basically four (!) copies of the same code living in this one function `get_swcBulk`: code maintenance becomes exceedingly tedious and error-prone. See my attempts to make `SOILWAT2` clean and lean: https://github.com/Burke-Lauenroth-Lab/SOILWAT2/milestone/3 and issues #84, #51, #31, and #30 and similar problems.

I am against copying code for only the tiniest change. I believe it is much better style to make the one copy slightly more general. e.g., `sw_error` or the macro`swprintf` which replaces `Rprintf` and `printf`

**Comment by BrendenBe1** [comment]
For the STEPPE flags I changed the time period from 
`p = t->month-1;`
to
`p = SW_Model.month-tOffset;`
This gets rid of the repeated month and does it correctly. I also made this same change for week.
Is there any reason why `p = t->month-1` was used over `p = SW_Model.month-tOffset;`?

**Comment by dschlaep** [comment]
I haven't worked with nor directed people to work on the STEPWAT2-flagged SOILWAT2 code. I don't know why the person who wrote the code in the STEPWAT2-flagged condition of this and similar output functions decided to define `SW_MODEL *t = &SW_Model` while the other logic-branches didn't.

In any case, yes, `t->month` and `SW_Model.month` should be equivalent.

Have you checked whether any other output function was affected and erroneously omitted `tOffset`?

**Comment by BrendenBe1** [comment]
Yes, all of the STEPPE code was using the old way which was overwriting indexes in the structures for month 10 and doing nothing for month 11. I am going to change all of those to use `p = SW_Model.month-tOffset;` instead so we can avoid this and also we can then remove the `SW_MODEL *t = &SW_Model;` initializations in every "get_*" function.

**Comment by dschlaep** [comment]
Great, thanks!

As you mentioned in an earlier comment, you will make those changes to both `SW_Model.month - tOffset;` and `SW_Model.week - tOffset;`.
